### ISSUE TITLE
Support for String tenant Id ?

### ISSUE THREAD

**Issue by ckthum** [multi-tenant/grails-multi-tenant-single-db#16] opened 2012-04-24 08:57 UTC
Hi,

I would like check whether there is any plan to support String(generated by UUID) for the tenant Id ?
It seems like lots of changes have to be made.  Thx.

Regards,
Thum

**Comment by kimble** [comment] 2012-04-24 17:31
Using strings for tenant id is probably not a good idea as the tenant id property will often be indexed (either alone or as part of a composite index).

**Comment by sronderos** [comment] 2013-04-07 18:06
If there is no compelling reason to support this change, could we close this issue?

**Comment by sronderos** [comment] 2015-03-14 00:53
Closing as duplicate of https://github.com/multi-tenant/grails-multi-tenant-single-db/issues/23

**Closed as completed by sronderos** 2015-03-14 00:53 UTC
Labels: enhancement
